name: event_booking
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  built_collection: ^4.3.2
  built_value: ^7.1.0
  http: ^0.12.1
  equatable: ^1.2.0
  flutter_bloc: ^4.0.1
  provider: ^4.1.3
  get_it: ^4.0.2
  flutter_secure_storage: ^3.3.3
  shared_preferences: ^0.5.7+3
  fluttertoast: ^4.0.1
  flutter:
    sdk: flutter


dev_dependencies:
  build_runner: ^1.10.0
  built_value_generator: ^7.1.0
  mockito: ^4.1.1
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
