name: event_booking
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  built_collection: ^4.3.2
  built_value: ^7.1.0
  flutter_login: ^1.0.14
  http: ^0.12.1
  equatable: ^0.4.0
  get_it: ^4.0.2
  dartz: ^0.9.1
  cupertino_icons: ^0.1.3
  flutter:
    sdk: flutter


dev_dependencies:
  build_runner: ^1.10.0
  built_value_generator: ^7.1.0
  flutter_test:
    sdk: flutter

  mockito: ^4.1.1

flutter:
  uses-material-design: true